apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: vjcmtz9y3-nodejs
  janus-idp.io/tekton: vjcmtz9y3-nodejs
  backstage.io/kubernetes-id: vjcmtz9y3-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: vjcmtz9y3-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
